amazoom/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^', include('web.urls', namespace='web')),
    url(r'^admin/', admin.site.urls),
]

amazoom/web/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import *

urlpatterns = [
	url(r'^$', ProductListView.as_view(), name='home'),
]

amazoom/web/models.py
from django.db import models


class Product(models.Model):
	name = models.CharField('Nombre', max_length=255)
	description = models.CharField('Descripción', max_length=1023)
	price = models.FloatField('Precio')

	def __str__(self):
		return self.name

amazoom/web/views.py
import requests
import json

from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.views.generic import TemplateView

from .models import Product


class ProductListView(TemplateView):
    template_name = 'product_list.html'

    def get(self, request, *args, **kwargs):
        context = {}
        context['object_list'] = requests.get('http://inventario:8001/api/product/list').json()
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
    	url = 'http://pagos:8003/api/payment/%s/' % request.POST['pk']
    	print(json.dumps(request.POST))
    	context = requests.post(url, data=dict(request.POST))
    	print(context)
    	print(context.json())
    	return HttpResponse(context)

amazoom/web/templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Amazoom</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>
  <body>
    <!--[if lt IE 8]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="{% url 'web:home' %}" class="navbar-brand">Amazoom</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar">
        </div>
      </div>
    </nav>
    <div class="container">
      {% block body %}
      {% endblock body %}
    </div>
    <script src="{% static 'js/jquery-1.12.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block script %}
    {% endblock script %}
  </body>
</html>

amazoom/web/templates/product_list.html
{% extends 'base.html' %}

{% load humanize %}

{% block body %}
<div class="row"> 
  {% for product in object_list %}
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="https://images6.alphacoders.com/718/thumb-1920-718467.jpg">
        <div class="caption">
          <h3>{{ product.name }}</h3>
          <p>{{ product.description }}</p>
          <p>
            <button type="button" class="btn btn-primary comprar" data-toggle="modal" data-target="#comprar" data-pk="{{ product.id }}">
              <i class="fa fa-shopping-cart"></i> Comprar
            </button>
            <label class="pull-right">$ {{ product.price|intcomma }}</label>
          </p>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

<!-- Modal -->
<div class="modal fade" id="comprar" tabindex="-1" role="dialog" aria-labelledby="comprarLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="comprarLabel">Comprar</h4>
      </div>
      <div class="modal-body">
        <form id="form" class="form-horizontal">
          {% csrf_token %}
          <input type="hidden" id="pk" name="pk" value="0">
          <div class="form-group">
            <label for="address" class="col-sm-2 control-label">Dirección</label>
            <div class="col-sm-10">
              <input type="email" class="form-control" name="address" id="address" required>
            </div>
          </div>
          <div class="form-group">
            <label for="amount" class="col-sm-2 control-label">Cantidad</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="amount" id="amount" required>
            </div>
          </div>
          <div class="form-group">
            <label for="card" class="col-sm-2 control-label">Nro. Tarjeta de Credito</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="card" id="card" required>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button id="comprar-btn" type="button" class="btn btn-primary">Comprar</button>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

{% block script %}
<script type="text/javascript">
  $(document).on('click', '.comprar', function() {
    console.log('OK' + $(this).attr('data-pk'))
    $('#pk').val($(this).attr('data-pk'));
  });
  $(document).on('click', '#comprar-btn', function() {
    var data = $('#form').serializeArray();
    console.log(data);
    $.ajax({
      url: '{{ request.get_full_path }}',
      type: 'POST',
      data: data
    })
    .done(function(response) {
      console.log(response);
      response = jQuery.parseJSON(response);
      if(response.hasOwnProperty('success')) {
        $('.modal').modal('hide');
        alert(response['success']);
      }
      if(response.hasOwnProperty('error')) {
        alert(response['error']);
      }
    })
    .fail(function() {
      alert('Ha ocurrido un error');
    });
  });
</script>
{% endblock script %}